### PR TITLE
fixing RNAdMobRewardedVideoAdModule to support latest version of React Native

### PR DESCRIPTION
**Pull request by fernandomatheus**
fixing this issue #295

### CODE REVIEW

**Comment by koenpunt** [comment]
I'm pretty sure this has nothing to do with the version of react native, and probably more with the version of Google Mobile Ads SDK

**Comment by koenpunt** [comment]
Maybe @jeongjuwon knows better since he added the method in #273

**Comment by gallan** [comment]
I was having the same issue using react-native-admob ^2.0.0-beta.5 in Android. Commenting out the Override line @fernandomatheus has in their PR worked for me, but doesn't work well with multiple developers when node_modules is in `.gitignore`. I wasn't sure how to update the "com.google.android.gms:play-services-ads dependency" as @koenpunt mentioned, but found that #324  helped me resolve the problem. I just added `maven { url "https://maven.google.com" }` to `android/build.gradle` under `buildscript` and `allprojects`.

**Comment by koenpunt** [comment]
Closing as stale.

**Pull request closed without merging**
