### PR TITLE
Support multiple test device IDs (backwards compatible)

### PR DESCRIPTION
**Pull request by ndbroadbent**
I renamed `testDeviceID` to `testDeviceIDs` and changed it to an array, so you can pass multiple test devices.

It is backwards compatible (with deprecation warnings), so you can still use `testDeviceID` for now.

### CODE REVIEW

**Comment by eranbes** [comment]
Can you please update it to current state so add the multiple test device ids to rewarded videos, too? Thanks.

**Comment by ndbroadbent** [comment]
Updated!

**Comment by ndbroadbent** [comment]
Rebased onto latest commit from master again

**Comment by Tiendq** [comment]
Please merge it, thanks.

**Comment by koenpunt** [comment]
v2 of the library (currently in beta) has a `testDevices` property which accepts an array of test devices.

You can install the latest beta version using:

    yarn add react-native-admob@next

Or

    npm install --save react-native-admob@next

**Pull request closed without merging**
