### PR TITLE
Fix cant click on iOS

### PR DESCRIPTION
**Pull request by jerson**
the frame must be on self not in _bannerView

### CODE REVIEW

**Comment by avishayil** [comment]
Doesn't work for me on DFP Publisher banner.

**Comment by nladd** [comment]
+1 fix worked for me using AdMobBanner. Would be great to get this change merged and released

**Comment by vnil** [comment]
Awesome! Thanks a lot!

**Comment by ndbroadbent** [comment]
@avishayil @jerson The same change needs to be applied to `ios/RNDFPBannerView.m`.

**Comment by ndbroadbent** [comment]
@jerson I pushed that fix to my own fork if you want to merge that in. See: https://github.com/ndbroadbent/react-native-admob/commit/c5e8252d573f37cce6e9efa01afd66195314d14f

**Comment by ayberkanilatsiz** [comment]
@ndbroadbent thx it worked ! 🎉

**Pull request merged**
