### PR TITLE
Native Express Ad

### PR DESCRIPTION
**Pull request by alexandrebini**

### CODE REVIEW

**Comment by chunghe** [comment]
Not sure if this is expected. But it will only render one AdMobNativeExpress even there's two in the same page. Here's the sample code:

```
      <View style={styles.container}>
        <AdMobNativeExpress
          adUnitID="ca-app-pub-3940256099942544/6300978111"
          bannerHeight={ height }
          bannerWidth={ width }
          testDeviceID="6AEB110BE6A410586E285465FABCCBE8"
          didFailToReceiveAdWithError={(e) => { console.log('didFailToReceiveAdWithError', e); }}
          adViewDidReceiveAd={(e) => {console.log('adViewDidReceiveAd', e)}}
        />
        <AdMobNativeExpress
          adUnitID="ca-app-pub-3940256099942544/6300978111"
          bannerHeight={ height }
          bannerWidth={ width }
          testDeviceID="6AEB110BE6A410586E285465FABCCBE8"
          didFailToReceiveAdWithError={(e) => { console.log('didFailToReceiveAdWithError', e); }}
          adViewDidReceiveAd={(e) => {console.log('adViewDidReceiveAd', e)}}
        />
      </View>
```

**Comment by chunghe** [comment]
full code:
```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import { AdMobNativeExpress, AdMobBanner } from 'react-native-admob';

const width = 360;
const height = 100;

export default class RN044 extends Component {
  render() {
    return (
      <View style={styles.container}>
        <AdMobNativeExpress
          adUnitID="ca-app-pub-3940256099942544/6300978111"
          bannerHeight={ height }
          bannerWidth={ width }
          testDeviceID="6AEB110BE6A410586E285465FABCCBE8"
          didFailToReceiveAdWithError={(e) => { console.log('didFailToReceiveAdWithError', e); }}
          adViewDidReceiveAd={(e) => {console.log('adViewDidReceiveAd', e)}}
        />
        <Text>---------------</Text>
        <AdMobNativeExpress
          adUnitID="ca-app-pub-3940256099942544/6300978111"
          bannerHeight={ height }
          bannerWidth={ width }
          testDeviceID="6AEB110BE6A410586E285465FABCCBE8"
          didFailToReceiveAdWithError={(e) => { console.log('didFailToReceiveAdWithError', e); }}
          adViewDidReceiveAd={(e) => {console.log('adViewDidReceiveAd', e)}}
        />

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});

AppRegistry.registerComponent('RN044', () => RN044);
```
screenshot:
screenshot_20170511-102641


There's no error occurred. The only thing log in the console is the `adViewDidReceiveAd` callback in the second `AdMobNativeExpress`. It seems if theres multiple `AdMobNativeExpress` in the same page, only the last one will display on the screen while others just begin ignored.

Otherwise, everything works perfectly, thank you for your hard work!

**Comment by alexandrebini** [comment]
@chunghe really weird... I have no ideia about how to fix it 😬

**Comment by alexandrebini** [comment]
@sbugert I won't have time to code the iOS version. Is this PR mergeable as it is?

Tks!

**Comment by ndbroadbent** [comment]
@alexandrebini I might be able to help with the iOS version, since this ad type looks really useful. But I gotta launch my app first, so maybe in the next few weeks.

**Comment by Dictory** [comment]
Ok, what about that future ? =)

**Comment by RatFou** [comment]
Hi, on my side Native Express Ads works but my app freeze for a while some times.

**Comment by patw0929** [comment]
Hi @alexandrebini
Is it possible to support the `fluid` size ads? Because I have to display ads on different size devices.
Thank you! 👍

**Comment by birgernass** [comment]
Hey @chunghe,
have you figured out how to display multiple ads per view?
Thanks in advance.

**Comment by chunghe** [comment]
@birgernass haven't figured out that yet :(

**Comment by alexandrebini** [comment]
Hi @patw0929 

The [doc](https://developers.google.com/admob/android/native-express#choose_a_size) says that `the AUTO_HEIGHT constant and FLUID ad size should not be used with Native Ads Express`.

But I think you can programmatically use [Dimensions#width](https://facebook.github.io/react-native/docs/dimensions.html#get)

**Comment by r0hit-gupta** [comment]
Google has now deprecated the Native Ads Express over Native Ads Advanced. I hope someone ports the Native Ads Advanced to RN. 
https://developers.google.com/admob/android/native-express

**Comment by koenpunt** [comment]
Closung per @r0hit-gupta comment.

**Pull request closed without merging**
