### PR TITLE
Fix "Argument list too long: recursive header expansion failed" issue

### LINKED ISSUE #209: Can't build due to "Argument list too long" error
When trying to run my app using `react-native run-ios`, I receive the following error:

```
=== BUILD TARGET RNAdMobManager OF PROJECT RNAdMobManager WITH CONFIGURATION Debug ===


Check dependencies

Argument list too long: recursive header expansion failed at /Users/gilad/MyProject/node_modules/react-native-admob/ios/../../../ios/Pods/React/node_modules/fsevents/node_modules/ajv/dist.



** BUILD FAILED **
```

I have the following in my `package.json`:
```
    "react-native-admob": "^2.0.0-beta.2",
```

And inside my `Podfile`:
```
  pod 'Google-Mobile-Ads-SDK'
```

I've tried to clean my `build` folder, as well as XCode's `DerivedData` - but it doesn't help...

### PR DESCRIPTION
**Pull request by angly-cat**
Fixes #209.

See [this comment](https://github.com/sbugert/react-native-admob/issues/209#issuecomment-344127065), and [this comment](https://github.com/tinycreative/react-native-intercom/issues/40#issuecomment-352094143).

### CODE REVIEW

**Comment by koenpunt** [comment]
Thank! Sorry for the late reply. Do you have any idea why this solves the issue?

**Comment by koenpunt** [comment]
Sounds acceptable. I'll see if I can make the search paths even more specific, and if that doesn't work I'll merge as-is. Thanks! 🚀

**Comment by evanjmg** [comment]
Please merge. I had to make these changes in my project

**Comment by evanjmg** [comment]
This worked at one point, now getting this 
```
Argument list too long: recursive header expansion failed at /Users/evanjmg/Desktop/development/cryptoBuyer/Bullish/node_modules/react-native-admob/ios/../../../ios/Pods/React/node_modules/react-tools/src/isomorphic/classic/element/__tests__
```

**Comment by angly-cat** [comment]
@evanjmg I had a lot of issues with my project as well, and the solution in my case was to stop including `react-native-*` packages as pods. When I started including them manually in Xcode, many issues are suddenly disappeared. It's slightly less convenient now than I'm unable to use `react-native link` command, but with some packages it was working incorrectly (like placing files in `Recovered References` section) anyway, and it's not like I include/exclude packages from my project often, so it was totally worth it.

**Comment by rawrmaan** [comment]
This change prevents the project from working properly with manual linking (no CocoaPods). It can't find the GoogleMobileAds framework.

**Comment by koenpunt** [comment]
@rawrmaan you have to add GoogleMobileAds to your project yourself.

**Comment by rawrmaan** [comment]
@koenpunt Yeah, I know. For some reason, this change prevents Xcode from finding the framework added to my project. I have my own branch where I reverted the change and it works perfectly.

**Pull request merged**
