### PR TITLE
feature: added Cocoapods support (podspec file + header fallback)

### PR DESCRIPTION
**Pull request by itchingpixels**
We're using Cocoapods with our RN project and created a .podspec file to ease the integration.

### CODE REVIEW

**Comment by koenpunt** [comment]
Great! I have been wanting to do this, will review ASAP

**Comment by itchingpixels** [comment]
this has been updated to resolve the conflicts with master

**Comment by koenpunt** [comment]
Unfortunately this only works for projects that do not use dynamic frameworks. So unless there's a way around that, I rather not confuse users with this additional constraint.

**Comment by koenpunt** [comment]
See also: https://github.com/CocoaPods/CocoaPods/issues/3985

**Comment by itchingpixels** [comment]
could we still merge, so we don't have to maintain a fork, and not
advertise this feature?

soon cocoapods will support static swift frameworks, so there'll be less
reason to use dynamic frameworks in general.

thank you!

**Comment by koenpunt** [comment]
> soon cocoapods will support static swift frameworks

Any timeline on that?

And until that's the case I prefer adding instructions on how to use it without `react-native link`, which is dragging the files from `./node_modules/react-native-admob/ios/` into a group in your project, instead of adding a semi-compatible `podspec`. 
And of course this isn't the optimal scenario, but at least it omits the need for you of maintaining a fork.

**Comment by itchingpixels** [comment]
I guess soon:
https://github.com/CocoaPods/CocoaPods/issues/6899
But no exact date at this point.

I think in general, use_frameworks! is not a common usecase when building a react-native app currently, I just tried it, and these libs are all failing to compile with dynamic frameworks enabled:
react-native-fabric
react-native-google-sign-in
react-native-onesignal
react-native-zendesk-support

Based on that, I presume adding the podspec would satisfy the main usecase, but I may be wrong.

Some of these libs do not specify that they support cocoapods, they just incldue a podspec - which is a clue for people who do use it (like ourselves) to try that :)

**Comment by koenpunt** [comment]
Well I expect most people not to use CocoaPods when using a React Native only project. So the people using CocoaPods are probably implementing it in an existing app, and when this app is written in Swift, and using Swift frameworks like `RealmSwift` or `DynamicColor`, there's no way gettings around using `use_frameworks!`. 

But at least a solution seems coming with the static framework support, so let's wait for that.

> Some of these libs do not specify that they support cocoapods, they just incldue a podspec - which is a clue for people who do use it (like ourselves) to try that :)

Same as above applies, if they are embedding RN in a Swift app, than this podspec probably won't work, and will raise questions on why this doesn't work, and in turn will result in issues here on GitHub, which is something I really want to prevent.

**Comment by koenpunt** [comment]
I might even add an excerpt to the README stating why CocoaPods is currently not supported.. But let's keep an eye on the development of the static frameworks support.

**Comment by koenpunt** [comment]
Nb. I actually would benefit using it through CocoaPods too, but since my project uses dynamic Swift frameworks I can't disable `use_frameworks!`, so I have added the files to my project manually for now.

**Comment by itchingpixels** [comment]
Understood.
I'm looking into making this work with use_frameworks! now.
I've found out that it should work by default, but unfortunately I mistakenly referenced the wrong pod name...
Google-AdMob-Ads-SDK 
vs Google-Mobile-Ads-SDK...

**Comment by koenpunt** [comment]
Well I guess that will work indeed, although it's weird that the `Google-AdMob-Ads-SDK` pod is documented. But since it functionality is simply pulling the library from http://dl.google.com/googleadmobadssdk/googlemobileadssdkios.zip I think that's OK.

**Comment by koenpunt** [comment]
Or no, that doesn't work, the latest version is not supported...

**Comment by koenpunt** [comment]
I've now added a podspec to the repo and released a new beta (`v2.0.0-beta.6`).

**Pull request closed without merging**
