### PR TITLE
Update SDK version to 26

### PR DESCRIPTION
**Pull request by emretekince**

### CODE REVIEW

**Comment by miltoneiji** [comment]
Why 26 and not 27 since for Android Gradle Plugin 3.1.4, the minimum supported version is 27?

**Comment by jugutier** [comment]
We could try using RN rootProject prop so that it matches whatever RN is using.

I believe 56 is not up to date and still only supports 26

```
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
```

**Comment by mdekrey** [comment]
See PR #393 for @jugutier's suggestion.

**Comment by koenpunt** [comment]
I've merged #393, so I think it should now be possible to override the value from the project implementing the library.

**Pull request closed without merging**
