### PR TITLE
Fix deployment target to match React Native (8.0)

### PR DESCRIPTION
**Pull request by ndbroadbent**
I figured this out when the build was crashing on my simulator running iOS 8.4. With help from [this comment on SO](http://stackoverflow.com/questions/32815121/dyld-symbol-not-found-nsdictionary0-when-using-google-servicegenerator-bi#comment53823443_32854141).

### CODE REVIEW

**Comment by alvaromb** [comment]
Hi @ndbroadbent!

Have you checked the implications of this change? Are the ads SDK supported for iOS 8.0?

**Comment by ndbroadbent** [comment]
Hi, I did test this on the iOS Simulator running iOS 8.4, and everything seemed to work fine.

I think the SDK supports iOS 7 and higher: https://firebase.google.com/docs/admob/ios/download

**Comment by philipheinser** [comment]
Also works for us with the target set to 8.0.

**Comment by alvaromb** [comment]
So, can we safely set the target to 8.0?

**Comment by alvaromb** [comment]
Ping @ndbroadbent @philipheinser

**Comment by ndbroadbent** [comment]
Hi, yes, should be totally safe to merge this. Apps cannot work on iOS 8 without this change.

**Comment by alvaromb** [comment]
Ok, @ndbroadbent, thanks for your quick feedback.

I'm in the middle of something, it's ok for you if we release this later this week?

**Comment by ndbroadbent** [comment]
Yes, no problem :) I am already just using a fork with my own changes, so I'm not in any hurry

**Comment by ndbroadbent** [comment]
@alvaromb sorry, just another ping on this. I just rebased to the latest commit on master

**Pull request merged**
