### PR TITLE
Rewarded ads support

### PR DESCRIPTION
**Pull request by alvaromb**
Tested with both iOS and Android. Corrected event name.

### CODE REVIEW

**Comment by alvaromb** [comment]
Hi @sbugert!

We're currently using in production this library with Rewarded Ads under iOS and Android. But there was an error with the rewarded event name. We have solved it.

However, there is more effort needed to update this library. How the library is handling the native events to JS is currently deprecated, and also we should update it to support RN 0.40.0. Please ping me if you need further help to merge this and to update the library.

**Comment by wasedaigo** [comment]
@alvaromb Do you have any fork? I am not sure when @sbugert is coming back... He is active on a private repo but nothing on this repo for three months.

**Comment by dkolba** [comment]
Hi @alvaromb, chiming in on @sbugert's behalf - we are currently in the middle of another urgent project and time is a little scarce.

Would you be willing to merge this yourself with commit access to this repo and npm?

**Comment by alvaromb** [comment]
@dkolba sure!

I would also give support to RN 0.40.0 with this release.

**Comment by dkolba** [comment]
@alvaromb by now you should have received an invitation from GitHub to become a collaborator, you also can publish this package on npm. 👍

**Comment by alvaromb** [comment]
Thanks @dkolba!

I'm currently out of the office till monday, expect a release next week.

**Comment by ndbroadbent** [comment]
Hi @alvaromb, I was just wondering if you had any time to merge this PR, and also the one for RN 0.40.x? (#78)

Sorry to bother you, but it looks like no-one else will be merging these

**Comment by alvaromb** [comment]
Hi @ndbroadbent!

I was on holidays, I just got back to work two days ago. Will try to do it this week!!

**Pull request merged**
