### PR TITLE
Support for React Native v0.40.0 in iOS platform

### PR DESCRIPTION
**Pull request by lucianomlima**
@sbugert this is a urgent fix. Stop build in Xcode and react-native CLI.

### CODE REVIEW

**Comment by alvaromb** [comment]
We could take this PR and expand it to solve the deprecated warnings in the `RCTEventDispatcher`.

**Comment by goodhyun** [comment]
Thanks for the PR, but the following fix was missing.

`#import <React/UIView+React.h>`

This line was also critical at least for my case. Seemingly unrelated module, yoga, was complaining.
`Duplicate interface definition for class 'RCTConvert'`

**Comment by lucianomlima** [comment]
@goodhyun thanks for the review! Fixed!

**Comment by 7kfpun** [comment]
Cannot be clicked on both iOS and Android. Anyone get the same?

**Comment by 7kfpun** [comment]
This would fix for iOS for clicking on banner.
https://github.com/sbugert/react-native-admob/pull/70/files

**Comment by ndbroadbent** [comment]
Hi @lucianomlima, I am testing your branch on iOS. I am still having a problem with the event callbacks. I think it is the same as #82. Would you be able to check if these working?

```
        <AdMobBanner
          style={styles.bannerAd}
          bannerSize={bannerSize}
          adUnitID={adUnitID}
          testDeviceID={testDeviceID}
          didFailToReceiveAdWithError={() => { console.log("error receiving ad") }}
          adViewWillPresentScreen={() => { console.log("presented ad") }}
          adViewDidReceiveAd={() => { console.log("received ad") }}
        />
```

I can take a look too. If I can figure it out, I might send a PR to your own branch.

**Comment by lucianomlima** [comment]
@ndbroadbent I will pull PR from here to my fork while @sbugert does not merge PRs here.
I tell you here but maybe I can't pull the PRs today.

**Comment by alvaromb** [comment]
@lucianomlima this is a breaking change that will make the package unable to work with RN version lower than 0.40.

**Comment by ndbroadbent** [comment]
@alvaromb Maybe we just need a note to the README. There are already some notes for `RN < 0.29`, `RN >= 0.29`, etc.

**Comment by alvaromb** [comment]
Closing in favour of #95, which has backwards compatibility with RN < 0.40.

**Pull request closed without merging**
